#Volume Name: claim-log-1
#Storage Request: 50Mi
#Access Modes: ReadWriteOnce
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim-log-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
